### ISSUE TITLE
Issue with numbers in translation keys

### ISSUE THREAD

**Issue by beerbohmdo** [kinglozzer/idea-silverstripe-plugin#12]
If a translation key includes numbers it will not be correctly be highlighted.

![image](https://user-images.githubusercontent.com/905241/112161192-2dfc0a80-8beb-11eb-9364-dee06a3be8f2.png)

**Comment by kinglozzer** [comment]
Thanks @beerbohmdo, fixed in 0.3.1 https://github.com/kinglozzer/idea-silverstripe-plugin/releases/tag/0.3.1
