### ISSUE TITLE
Highlight closing tag

### ISSUE THREAD

**Issue by beerbohmdo** [kinglozzer/idea-silverstripe-plugin#18]
Would it be possible to highlight the corresponding close tags, as it is already the case for normal html elements?

I thought that this worked in the past.

**Comment by kinglozzer** [comment]
I think this should be possible, the tag pairs are already identifiable as the collapse functionality requires that.

**Comment by kinglozzer** [comment]
I’ve implemented this in 1.0.1 which is pending approval. When you have a tag highlighted, both the opening and closing tags should be highlighted the same colour
