### ISSUE TITLE
Translation tags

### ISSUE THREAD

**Issue by mikaldl** [kinglozzer/idea-silverstripe-plugin#20]
Eventhough it's not the recommended way of using the i18n like that; it works and it's way nicer than being creative with the names, I really would like to have this not throw an error. (or atleast have a way to ignore it)

![image](https://user-images.githubusercontent.com/14072441/124482044-30086480-dda9-11eb-93d8-ca578e491a53.png)

Multiple dots are the problem; which makes the entire block failing.

**Comment by kinglozzer** [comment]
Thanks, I’d normally reject something like this as it’s best to stick to Silverstripe’s conventions... but in this case, the template parser definitely allows it and it’s a simple change. It should work as you’re expecting in 1.0.1 when the update is approved 😃

**Comment by mikaldl** [comment]
Thanks for the quick fix! Looking forward to see the update :)
