### ISSUE TITLE
Incorrectly Marking Blocks as Incomplete

### ISSUE THREAD

**Issue by jchenevey** [kinglozzer/idea-silverstripe-plugin#21]
The plugin is marking some blocks for me as incomplete, even though they are.

See attached Layout file (with added .txt extension so Github will let me upload it), and screenshot showing highlighting.

[HealthAndWellnessPage.ss.txt](https://github.com/kinglozzer/idea-silverstripe-plugin/files/7016485/HealthAndWellnessPage.ss.txt)

![Screen Shot 2021-08-19 at 1 17 19 PM](https://user-images.githubusercontent.com/8449994/130114168-10738010-430b-4d1a-872a-736b08e64554.png)

**Comment by kinglozzer** [comment]
I’ve had a quick look, it looks like it’s the image tag that’s throwing it off:

```html
<div class="featured-image">
    <img class="img img-fluid" src="{$FeaturedImage.Fill(247.5,165).Link}" alt="{$FeaturedImage.Title}" />
</div>
```

If I remove the decimal point from the dimensions it’s fine, so it looks like it’s failing to parse float arguments properly
