### ISSUE TITLE
Icon colour

### ISSUE THREAD

**Issue by TimBBP** [kinglozzer/idea-silverstripe-plugin#27]
OK, granted this is a minor one!    

The Silverstripe icon in the files list is currently showing up in black on my system.   It's probably OK if you're on a light theme, but on mine (which is a dark theme) it's a bit nasty.

Just wondering if the S should be blue.. not sure what the brand guidelines say about it.

![Screenshot from 2023-08-08 17-14-47](https://github.com/kinglozzer/idea-silverstripe-plugin/assets/79973633/5f238f69-3746-4c3f-a638-74a9d9bd81ee)
![Screenshot from 2023-08-08 17-08-36](https://github.com/kinglozzer/idea-silverstripe-plugin/assets/79973633/beca1eb3-5385-4d31-a13a-0adfa2c212ce)

**Comment by kinglozzer** [comment]
Hmm that’s weird, the icon should be blue! https://github.com/kinglozzer/idea-silverstripe-plugin/blob/master/src/main/resources/icons/silverstripe.svg. It seems the 2023.1 -> 2023.2 update is where this broke 😞 

I do actually want to look at updating the icon soon anyway, as the open source product is [getting its own branding](https://github.com/silverstripe/silverstripe-admin/issues/1542) so I’ll double check the icon guidelines in case I’ve missed something

**Comment by kinglozzer** [comment]
Hmm that’s odd, mine are now appearing correctly after indexing has finished. I’m wondering if it’s a conflict between two plugins - do you have any other plugins that might be adding custom icons?

**Comment by kinglozzer** [comment]
I’ve updated the icons in 1.0.4 (pending approval, but can be installed from ZIP via GitHub) and that has resolved this for me

**Comment by TimBBP** [comment]
That's sorted it for me too, cheers Loz.

![Screenshot from 2023-08-14 15-23-29](https://github.com/kinglozzer/idea-silverstripe-plugin/assets/79973633/3c4baf4d-2d9e-48f2-a198-e46e3e9e0272)

**Comment by patricknelson** [comment]
Commented on [e71767c](https://github.com/kinglozzer/idea-silverstripe-plugin/commit/e71767c0effceaf0cf8fa6ca55feb9f725d517ed) but maybe this is a better (more visible) spot: 

> ... the new icon looks slick.
> 
> Curious though: Where does it come from, is it specific to this plugin (i.e. this plugin's own icon) or did SS rebrand? Not seeing it yet on silverstripe.org or on SS repos ([the org](https://github.com/silverstripe) at least).

**Comment by patricknelson** [comment]
Deleted my comment, just saw the link above to https://github.com/silverstripe/silverstripe-admin/issues/1542.

I was wondering why the icon changed, if SS was getting a new logo, since it isn't yet on the actual SilverStripe website nor Github organization page. 😅
