### ISSUE TITLE
Default template includes not found

### ISSUE THREAD

**Issue by HJGreen** [kinglozzer/idea-silverstripe-plugin#6]
- **PHPStorm version**: 2020.3.2
- **Plugin version**: 0.0.1

Given a theme structure:
```
templates/
    Includes/
        MyInclude.ss
    Logos/
        MyLogo.ss
    Page.ss
```

Where `Page.ss` contains:
```
<%-- This include does not link to the template file --%>

<% include MyInclude %>    


<%-- Using the full namespace works as expected --%>

<% include Includes\MyInclude %>
<% include Logos\MyLogo %>
```

The first include tag doesn't link to the referenced template
  - Template name is greyed out
  - Can't Cmd + Click to jump to the file
  - Hovering gives `Couldn't find include "MyInclude.ss"`

**Comment by kinglozzer** [comment]
Thanks @HJGreen, I’ve released 0.0.2 which should fix this
